- id: '1584476995764'
  alias: Notify me if Kirstyn arrives
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.dyson_parkes
    state: not_home
  action:
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.html5_notifications
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.mobile_app_bnet_a74
  initial_state: 'off'
  mode: single
- id: '1597613199016'
  alias: 'Lovelace: convert lovelace.json to lovelace-ui.yaml'
  description: Convert lovelace.json to lovelace-ui.yaml
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
    context:
      user_id:
      - 08d29e434e9a4bed98b3a62218eac7a7
  action:
  - service: shell_command.convert_lovelace
  mode: single
- id: '1602904795038'
  alias: Notify me on update availability
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.html5_notifications
    data:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
      title: Update Available
  - service: notify.discord
    data:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
      title: Update Available!
      target:
      - '819351502640381952'
  mode: single
- id: '1603249243832'
  alias: Commit changes to Github
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.git_commit
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: shell_command.commit_changes
    data: {}
  - service: input_text.set_value
    data:
      value: Committed from UI without a message
    entity_id: input_text.git_message
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.git_commit
  mode: single
- id: '1603311446063'
  alias: 'Lovelace: convert json to yaml and commit'
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  condition: []
  action:
  - service: shell_command.convert_lovelace
  - delay: '5'
  - service: shell_command.commit_lovelace
    data: {}
  initial_state: 'off'
  mode: single
- id: '1605335470308'
  alias: SWMBO home and away
  description: Is she home or isn't she?
  trigger:
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: home
    to: not_home
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: not_home
    to: home
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Kirstyn
      title: Kirstyn is {{ trigger.to_state.state }}
      message: Kirstyn went from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }} at {{ now().strftime('%H:%M %d/%m/%Y') }}
  mode: single
- id: '1608262512161'
  alias: Happy Birthday Sir
  description: A silly little automation to have HAss wish me happy birthday
  trigger:
  - platform: state
    entity_id: sensor.birthday_me
    to: '0'
    for: '"07:00:00"'
  condition: []
  action:
  - service: notify.notify
    data:
      message: Happy Birthday Sir!
      title: Bappy Hirthday
  mode: single
- id: '1608262874242'
  alias: Birthday Reminders
  description: Remind me of upcoming birthdays
  trigger:
  - platform: state
    entity_id: sensor.birthday_swmbo,sensor.birthday_me
    to: '1'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Birthday
      title: Upcoming birthday!
      message: '''{{trigger.to_state.attributes.friendly_name}} is tomorrow!'''
  mode: single
- id: '1608606143148'
  alias: Install additional packages
  description: Installs packages defined in a shell script
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: 00:00:10
  - service: shell_command.install_extra_packages
    data: {}
  mode: single
- id: '1611959876984'
  alias: BTC Alert
  description: Notify me if BTC goes above a certain value
  trigger:
  - platform: numeric_state
    entity_id: sensor.exchange_rate_1_btc
    above: '85000'
  action:
  - service: notify.mobile_app_g8142
    data:
      message: BTC just went up to ${{ states.sensor.exchange_rate_1_btc.state }}
      title: BTC Value
  - service: notify.discord
    data:
      message: BTC just went up to ${{ states.sensor.exchange_rate_1_btc.state }}
      target: '819351502640381952'
  mode: single
- id: '1618826864131'
  alias: Welcome Home Sir
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: media_player.str_dn1080_9ba8db_2
    state: 'false'
    attribute: is_volume_muted
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.str_dn1080_9ba8db_2
  - wait_template: ''
    continue_on_timeout: true
    timeout: '3'
  - service: media_player.play_media
    data:
      media_content_id: media-source://media_source/local/sir-im-afraid-hes-insisting.wav
      media_content_type: music
    target:
      entity_id: media_player.str_dn1080_9ba8db
  - wait_template: ''
    timeout: '12'
    continue_on_timeout: true
  - service: media_player.select_source
    target:
      entity_id: media_player.str_dn1080_9ba8db_2
    data:
      source: VIDEO 1
  - service: media_player.turn_off
    target:
      entity_id: media_player.str_dn1080_9ba8db_2
  mode: single
- id: '1621926272836'
  alias: 'Turn on the lights when I get home '
  description: ''
  trigger:
  - platform: zone
    entity_id: person.dyson_parkes
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: light.turn_on
    target:
      area_id:
      - ebfb50d4d7f14ca58bb27f3b2694979c
      - 8395b9f7ecad4aca90b4a4841fe57df7
  mode: single
- id: '1623151855818'
  alias: Sync sub power with amp
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.str_dn1080_9ba8db_2
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: media_player.str_dn1080_9ba8db_2
    from: 'on'
    to: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.str_dn1080_9ba8db_2
        state: 'on'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.subwoofer
    - conditions:
      - condition: state
        entity_id: media_player.str_dn1080_9ba8db_2
        state: 'off'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
    default: []
  mode: single
