- id: '1584476995764'
  alias: Notify me if Kirstyn arrives when I am not at home
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.html5_notifications
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.mobile_app_g8142
  mode: single
- id: '1597613199016'
  alias: 'Lovelace: convert lovelace.json to lovelace-ui.yaml'
  description: Convert lovelace.json to lovelace-ui.yaml
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  action:
  - service: shell_command.convert_lovelace
  mode: single
- id: '1602904795038'
  alias: Notify me on update availability
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.notify
    data:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
  mode: single
- id: '1603249243832'
  alias: Commit changes to Github
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.git_commit
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: shell_command.commit_changes
    data: {}
  - service: input_text.set_value
    data:
      value: Committed from UI without a message
    entity_id: input_text.git_message
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.git_commit
  mode: single
- id: '1603311446063'
  alias: 'Lovelace: convert json to yaml and commit'
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  condition: []
  action:
  - service: shell_command.convert_lovelace
  - delay: '5'
  - service: shell_command.commit_lovelace
    data: {}
  initial_state: 'off'
  mode: single
- id: '1605335470308'
  alias: SWMBO home and away
  description: Is she home or isn't she?
  trigger:
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: home
    to: not_home
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: not_home
    to: home
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Kirstyn
      title: Kirstyn is {{ trigger.to_state.state }}
      message: Kirstyn went from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }} at {{ now().strftime('%H:%M %d/%m/%Y') }}
  mode: single
  initial_state: 'off'
- id: '1608262512161'
  alias: Happy Birthday Sir
  description: A silly little automation to have HAss wish me happy birthday
  trigger:
  - platform: state
    entity_id: sensor.birthday_me
    to: '0'
    for: '"07:00:00"'
  condition: []
  action:
  - service: notify.notify
    data:
      message: Happy Birthday Sir!
      title: Bappy Hirthday
  mode: single
- id: '1608262874242'
  alias: Birthday Reminders
  description: Remind me of upcoming birthdays
  trigger:
  - platform: state
    entity_id: sensor.birthday_swmbo,sensor.birthday_me
    to: '1'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Birthday
      title: Upcoming birthday!
      message: '''{{trigger.to_state.attributes.friendly_name}} is tomorrow!'''
  mode: single
