- id: '1584476995764'
  alias: Notify me if Kirstyn arrives when I am not at home
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.html5_notifications_workpc
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.mobile_app_g8142
  mode: single
- id: '1590888183776'
  alias: Convert Lovelace configuration to yaml
  description: ''
  trigger:
  - event_data:
      event_type: modified
    event_type: folder_watcher
    platform: event
  condition: []
  action:
  - service: shell_command.llconvert
- id: '1597613199016'
  alias: 'Lovelace: convert lovelace.json to lovelace-ui.yaml'
  initial_state: 'on'
  description: Convert lovelace.json to lovelace-ui.yaml
  trigger:
  - entity_id: sensor.lovelace
    platform: state
  action:
  - service: shell_command.convert_lovelace
  mode: single
