- id: '1584476995764'
  alias: Notification - SWMBO Arrives
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    platform: state
    to: home
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dyson_parkes
      state: home
    alias: Confirm Dyson is out
  action:
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.mobile_app_bnet_a74
    alias: Mobile notification
  - service: notify.html5_notifications
    data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    alias: Browser notification
  mode: single
- id: '1597613199016'
  alias: 'Lovelace: convert lovelace.json to lovelace-ui.yaml'
  description: Convert lovelace.json to lovelace-ui.yaml
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
    context:
      user_id:
      - 08d29e434e9a4bed98b3a62218eac7a7
  action:
  - service: shell_command.convert_lovelace
  mode: single
- id: '1602904795038'
  alias: Notification - HAss Update Available
  description: ''
  trigger:
  - platform: state
    entity_id:
    - update.home_assistant_core_update
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - service: notify.html5_notifications
    data:
      message: Home Assistant {{ state_attr('update.home_assistant_core_update', 'latest_version')
        }} is available.
      title: Update Available
    alias: Browser notification
  - service: notify.homeassistant
    data:
      message: Home Assistant {{ state_attr('update.home_assistant_core_update', 'latest_version')
        }} is available.
      title: Update Available!
      target:
      - '819351502640381952'
    alias: Discord notification
  - service: notify.facebook_text
    data:
      message: Home Assistant {{ state_attr('update.home_assistant_core_update', 'latest_version')
        }} is available.
    alias: Facebook notification
  mode: single
- id: '1603249243832'
  alias: Github - Commit Changes
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.git_commit
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: shell_command.commit_changes
    data: {}
  - service: input_text.set_value
    data:
      value: Committed from UI without a message
    entity_id: input_text.git_message
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.git_commit
  mode: single
- id: '1603311446063'
  alias: Github - Convert Lovelace json to yaml and commit
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  condition: []
  action:
  - service: shell_command.convert_lovelace
  - delay: '5'
  - service: shell_command.commit_lovelace
    data: {}
  initial_state: false
  mode: single
- id: '1605335470308'
  alias: Notification - SWMBO home and away
  description: Is she home or isn't she?
  trigger:
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: home
    to: not_home
  - platform: state
    entity_id: person.kirstyn_rolfe
    from: not_home
    to: home
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Kirstyn
      title: Kirstyn is {{ trigger.to_state.state }}
      message: Kirstyn went from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }} at {{ now().strftime('%H:%M %d/%m/%Y') }}
  mode: single
- id: '1608262512161'
  alias: Notification - Happy Birthday Sir
  description: A silly little automation to have HAss wish me happy birthday
  trigger:
  - platform: state
    entity_id:
    - sensor.birthday_me
    to: '0'
    for:
      hours: 7
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - service: notify.notify
    data:
      message: Happy Birthday Sir!
      title: Bappy Hirthday
  mode: single
- id: '1608262874242'
  alias: Notification - Birthday Reminders
  description: Remind me of upcoming birthdays
  trigger:
  - platform: state
    entity_id:
    - sensor.birthday_swmbo
    - sensor.birthday_me
    to: '1'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      notification_id: Birthday
      title: Upcoming birthday!
      message: '''{{trigger.to_state.attributes.friendly_name}} is tomorrow!'''
  mode: single
- id: '1608606143148'
  alias: System - Install additional packages
  description: Installs packages defined in a shell script
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: 00:00:10
  - service: shell_command.install_extra_packages
    data: {}
  mode: single
  initial_state: false
- id: '1618826864131'
  alias: Notification - Welcome Home Sir
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.dyson_parkes
    to: home
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  - condition: time
    before: '23:00:00'
    after: 08:00:00
    alias: Not nighttime
  - condition: not
    conditions:
    - condition: state
      entity_id: person.kirstyn_rolfe
      state: home
      alias: Kirstyn location check
    alias: Kirstyn isn't home
  action:
  - service: notify.alexa_media_lounge_dot
    data:
      data:
        type: tts
        target: media_player.lounge_dot
      message: Welcome home m'lord
    alias: Welcome home via lounge dot
    enabled: false
  - service: notify.alexa_media_doppler
    data:
      data:
        type: tts
        target: media_player.doppler
      message: Welcome home m'lord
    alias: Welcome home via doppler
    enabled: true
  mode: single
- id: '1621926272836'
  alias: Lights - Turn on to greet me
  description: ''
  trigger:
  - platform: zone
    entity_id: person.dyson_parkes
    zone: zone.home
    event: enter
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunrise
      after: sunset
      alias: Confirm the sun's not up
    - condition: state
      entity_id: input_boolean.silent_mode
      state: 'off'
  action:
  - service: light.turn_on
    data:
      transition: 2
    target:
      entity_id: light.lifx_switch_6c31d6_porch
  - service: light.turn_on
    data:
      transition: 2
      brightness_pct: 100
    target:
      entity_id: light.bedroom
    enabled: false
  mode: single
- id: '1623151855818'
  alias: Amp Power - Sync sub with amp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.lounge_amp_3
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_3
        state: 'off'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
        data: {}
    - conditions:
      - condition: state
        state: standby
        entity_id: media_player.lounge_amp_3
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
        data: {}
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_3
        state: idle
        enabled: true
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
        data: {}
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_3
        state: unavailable
        enabled: true
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
        data: {}
    default:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.subwoofer
  mode: single
- id: '1635829545674'
  alias: Notification - SWMBO Leaves
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: 'Kirstyn just left '
      title: Kirstyn's gone
    service: notify.html5_notifications
    alias: Browser notification
  - data:
      message: Kirstyn just left
      title: Kirstyn's gone
    service: notify.mobile_app_bnet_a74
    alias: Mobile notification
  mode: single
  initial_state: false
- id: '1638231245218'
  alias: Notification - HACS Updates Available
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: '0'
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - service: persistent_notification.create
    data:
      notification_id: hacs_updates
      title: HACS Update
      message: Updates available in {{ states('sensor.hacs') }} [HACS repo{% if states('sensor.hacs')
        | int > 1 %}s{% endif %}](/hacs)
  - service: notify.facebook_text
    data:
      message: Updates available in {{ states('sensor.hacs') }} HACS repo{% if states('sensor.hacs')
        | int > 1 %}s{% endif %} {% for repo in states.sensor.hacs.attributes.repositories
        %} {{ repo.name }} {% endfor %}
    alias: Facebook notification
  - service: notify.homeassistant
    data:
      message: 'Updates available in {{ states(''sensor.hacs'') }} HACS repo{% if
        states(''sensor.hacs'') | int > 1 %}s{% endif %}\: {% for repo in states.sensor.hacs.attributes.repositories
        %} {{repo.name }}, {{repo.installed_version}} -> {{repo.available_version}}
        {% endfor %}'
      title: HACS Updates available
      target:
      - '819351502640381952'
    alias: Discord notification
  mode: single
- id: '1638232674502'
  alias: Notification - HACS Updates Installed
  description: Dismiss persistent_notification for hacs updates
  trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    below: '1'
  condition: []
  action:
  - service: persistent_notification.dismiss
    data:
      notification_id: hacs_updates
  mode: single
- id: '1639688722323'
  alias: Amp Power - Sync sub with amp (on startup)
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: media_player.lounge_amp_3
          state: 'off'
          alias: Confirm lounge amp is not off
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.subwoofer
        data: {}
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_3
        state: 'off'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.subwoofer
        data: {}
    default: []
  mode: single
- id: '1641896084660'
  alias: Media - Play all music
  description: Shuffles all music from system /media/Music folder
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_boolean.silent_mode
      state: ''
  action:
  - service: media_player.clear_playlist
    target:
      entity_id: media_player.vlc_telnet
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.vlc_telnet
    data:
      shuffle: true
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_type: music
      media_content_id: /media/Music
  mode: single
  initial_state: false
- id: '1651206195438'
  alias: Notification - HAssOS Update Available
  description: ''
  trigger:
  - platform: state
    entity_id:
    - update.home_assistant_operating_system_update
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  action:
  - service: notify.html5_notifications
    data:
      message: Home Assistant OS {{ state_attr('update.home_assistant_operating_system_update',
        'latest_version') }} is available.
      title: Update Available
    alias: Browser notification
  - service: notify.homeassistant
    data:
      message: Home Assistant OS {{ state_attr('update.home_assistant_operating_system_update',
        'latest_version') }} is available.
      title: Update Available!
      target:
      - '819351502640381952'
    alias: Discord notification
  - service: notify.facebook_text
    data:
      message: Home Assistant OS {{ state_attr('update.home_assistant_operating_system_update',
        'latest_version') }} is available.
    alias: Facebook notification
  mode: single
- id: '1655351847580'
  alias: Amp Volume - Change Input
  description: Changes volume on the Lounge amplifier to suit whatever levels are
    received from the differing sources
  trigger:
  - platform: state
    entity_id:
    - media_player.lounge_amp_2
    for:
      hours: 0
      minutes: 0
      seconds: 0
    attribute: media_title
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_2
        attribute: media_title
        state: BD/DVD
        for:
          hours: 0
          minutes: 0
          seconds: 0
        alias: PC (BD/DVD)
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.lounge_amp_2
        data:
          volume_level: 0.73
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_2
        attribute: media_title
        state: GAME
        for:
          hours: 0
          minutes: 0
          seconds: 0
        alias: PS5 (GAME)
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.lounge_amp_2
        data:
          volume_level: 0.27
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_2
        attribute: media_title
        state: SA-CD/CD
        for:
          hours: 0
          minutes: 0
          seconds: 0
        alias: Xbox SX (SA-CD/CD)
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.lounge_amp_2
        data:
          volume_level: 0.335
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_2
        attribute: media_title
        state: VIDEO 2
        for:
          hours: 0
          minutes: 0
          seconds: 0
        alias: Xbox One (VIDEO 2)
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.lounge_amp_2
        data:
          volume_level: 0.335
    - conditions:
      - condition: state
        entity_id: media_player.lounge_amp_2
        attribute: media_title
        state: TV
        for:
          hours: 0
          minutes: 0
          seconds: 0
        alias: TV
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.lounge_amp_2
        data:
          volume_level: 0.27
    default: []
  mode: single
- id: '1665709420254'
  alias: Doppler - Button 1
  description: Toggles a light on push of Doppler smart button 1
  trigger:
  - platform: device
    domain: sandman_doppler
    device_id: 71b40ef41901e6650f2ec43ddd2b63dc
    button: 1
    type: sandman_doppler_button_pressed
    subtype: 1
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_light
  mode: single
- id: '1665709479272'
  alias: Doppler - Button 2
  description: Toggles a light on push of Doppler smart button 2
  trigger:
  - platform: device
    domain: sandman_doppler
    device_id: 71b40ef41901e6650f2ec43ddd2b63dc
    button: 2
    type: sandman_doppler_button_pressed
    subtype: 2
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_lamp
  mode: single
- id: '1666768764502'
  alias: Printer - Notify if out of paper
  description: Talks through the speakers to notify if the printer runs out of paper
  trigger:
  - platform: state
    entity_id:
    - sensor.mfc_9340cdw_status
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  - condition: time
    before: '23:00:00'
    after: 08:00:00
    alias: Not nighttime
  action:
  - service: notify.alexa_media_dyson_s_echo_dot
    data:
      data:
        type: tts
        target: media_player.dyson_s_echo_dot
      message: The printer has run out of paper
    alias: Printer status via lounge dot
    enabled: true
  mode: single
- id: '1670119294104'
  alias: Notification - Kettle boiled
  description: Talks through the speakers to notify if the jug has boiled
  trigger:
  - platform: numeric_state
    entity_id: sensor.kettle_temperature
    above: 98
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition:
  - condition: state
    entity_id: input_boolean.silent_mode
    state: 'off'
  - condition: time
    before: '23:00:00'
    after: 08:00:00
    alias: Not nighttime
  action:
  - service: notify.alexa_media_dyson_s_echo_dot
    data:
      data:
        type: tts
        target: media_player.dyson_s_echo_dot
      message: The kettle has finished boiling
    alias: Jug boiled
    enabled: true
  mode: single
- id: '1679630068333'
  alias: 1-NSPanel Configuration
  description: ''
  use_blueprint:
    path: Blackymas/nspanel_blueprint.yaml
    input:
      language: ENG
      nspanel_name: devpanel
      delay: 4
      weather: AccuWeather
      weather_entity: weather.home
      left_button_entity: light.office_light
      left_button_name: Light
      right_button_entity: light.office_lamp
      right_button_name: Lamp
- id: '1688357078253'
  alias: Garage Lights (Switch toggle all)
  description: Allows the bottom switch on the garage panel to toggle all lights in
    the area.
  trigger:
  - platform: device
    device_id: 06ba335d596e242b91bb5ffd677c8d0e
    domain: homekit_controller
    type: button4
    subtype: single_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      area_id: garage
  mode: single
- id: '1694906150147'
  alias: Automation - empty the house
  description: Turn off all lights when the last person leaves the house
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.bnet_a74_wifi_connection
      state: Berserkir-Net
    alias: Confirm phone is not on home wifi
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.all_lights
      - light.all_lamps
  mode: single
