- id: '1584476995764'
  alias: Notify me if Kirstyn arrives when I am not at home
  description: ''
  trigger:
  - entity_id: person.kirstyn_rolfe
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.html5_notifications
  - data:
      message: Kirstyn just arrived
      title: Kirstyn's Home
    service: notify.mobile_app_g8142
  mode: single
- id: '1597613199016'
  alias: 'Lovelace: convert lovelace.json to lovelace-ui.yaml'
  description: Convert lovelace.json to lovelace-ui.yaml
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  action:
  - service: shell_command.convert_lovelace
  initial_state: 'on'
  mode: single
- id: '1602904795038'
  alias: Notify me on update availability
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.notify
    data:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
  mode: single
- id: '1603249243832'
  alias: Commit changes to Github
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.git_commit
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: shell_command.commit_changes
    data: {}
  - service: input_text.set_value
    data:
      value: Committed from UI without a message
    entity_id: input_text.git_message
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.git_commit
  mode: single
