
# Configure a default setup of Home Assistant (frontend, api, etc)
# This is used for a recovery boot
default_config:
# Uncomment this if you are using a reverse proxy
  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - !secret server_1_ip
      - !secret server_2_ip

## Simple Components
map:
met:
sun:
updater:
wake_on_lan:

## Complex Components
#Custom config directives
homeassistant:
  allowlist_external_dirs:
    - /config/.storage

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
# HTTP (sets allowed proxies, reverse proxy options)
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_1_ip
    - !secret server_2_ip
## Frontend
frontend:
  themes: !include_dir_merge_named themes

## Includes
# All Files in Folder (save each type in the relevant directory)
group: !include_dir_merge_list groups
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
#template: !include_dir_merge_list templates
zone: !include_dir_merge_list zones
# Single Files
automation: !include automations.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_datetime: !include includes/input_datetime.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include includes/shell_commands.yaml
# Specific Integration types (save all under individuals/%name%.yaml)
light: !include includes/lights.yaml
nzbget: !include includes/nzbget.yaml
ombi: !include includes/ombi.yaml
pi_hole: !include includes/communica_pihole.yaml
spotify: !include includes/spotify.yaml

#################################################################
## Testing functions
#camera: !include individuals/unifi_video.yaml
#influxdb: !include individuals/influxdb.yaml #disabled for system load
#octoprint: !include individuals/octoprint.yaml
