
# Configure a default setup of Home Assistant (frontend, api, etc)
# This is used for a recovery boot
default_config:
# Uncomment this if you are using a reverse proxy
  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - !secret trusted_proxy1
      - !secret trusted_proxy2

## Simple Components
map:
met:
sun:
updater:
wake_on_lan:

## Complex Components
#Custom config directives
homeassistant:
  allowlist_external_dirs:
    - /config/.storage

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
# HTTP (sets allowed proxies, reverse proxy options)
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy1
    - !secret trusted_proxy2
## Frontend
frontend:
  themes: !include_dir_merge_named themes

## Includes
# All Files in Folder (save each type in the relevant directory)
device_tracker: !include_dir_merge_list device_trackers
folder_watcher: !include_dir_merge_list folder_watchers
group: !include_dir_merge_list groups
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zones
automation: !include automations.yaml
# Single Files
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include includes/shell_commands.yaml
# Specific Integration types (save all under individuals/%name%.yaml)
light: !include includes/lights.yaml
nzbget: !include includes/nzbget.yaml
ombi: !include includes/ombi.yaml
pi_hole: !include includes/communica_pihole.yaml
spotify: !include includes/spotify.yaml

#################################################################
## Testing functions
#template: !include_dir_merge_named templates
#camera: !include individuals/unifi_video.yaml
#influxdb: !include individuals/influxdb.yaml #disabled for system load
#octoprint: !include individuals/octoprint.yaml
