# Configure a default setup of Home Assistant (frontend, api, etc)
# This is used for a recovery boot
default_config:
  # This tells HAss that it should still accept reverse proxy info when it does a recovery boot.
  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - !secret server_1_ip
      - !secret server_2_ip
      - !secret server_3_ip
## Simple Components
map:
met:
sun:
updater:
wake_on_lan:

## Complex Components
#Custom config directives
homeassistant:
  allowlist_external_dirs:
    - /config/.storage
    - /config
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_network

# HACS Browser Mod
browser_mod: !include includes/browser_mod.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
# HTTP (sets allowed proxies, reverse proxy options)
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_1_ip
    - !secret server_2_ip
    - !secret server_3_ip
## Frontend
frontend:
  themes: !include_dir_merge_named themes

## Includes
# All Files in Folder (save each type in the relevant directory)
group: !include_dir_merge_list groups
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zones
# Single Files / Direct includes (All saved in the includes directory)
anniversaries: !include includes/anniversaries.yaml
#coinbase: !include includes/coinbase.yaml
hdhomerun: !include includes/hdhomerun.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_datetime: !include includes/input_datetime.yaml
light: !include includes/lights.yaml
nzbget: !include includes/nzbget.yaml
#octoprint: !include includes/octoprint.yaml
ombi: !include includes/ombi.yaml
pi_hole: !include includes/communica_pihole.yaml
recorder: !include includes/recorder.yaml
shell_command: !include includes/shell_commands.yaml
spotify: !include includes/spotify.yaml
tplink: !include includes/tplink.yaml
# Root includes (these files do not handle being moved at all - some are edited by the system itself)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#################################################################
## Testing functions
#camera: !include individuals/unifi_video.yaml
#influxdb: !include individuals/influxdb.yaml #disabled for system load
