button_card_templates:
  inkwell:
    extra_styles: "[[[ return `\n  @keyframes pulse {\n    5% {\n      background-color:\
      \ ${variables.color};\n    }\n  }\n`]]]\n"
    show_name: false
    show_state: true
    styles:
      card:
      - border: solid 3px gray
      - border-top: none
      - background: "[[[\n  var level = entity.state;\n  var color = variables.color;\n\
          \  return `linear-gradient(to top, ${color}, ${color} ${level}%, rgba(255,255,255,0.12)\
          \ ${level}%)`\n]]]\n"
      - animation: "[[[\n  return (0 + entity.state) < 10\n    ? 'pulse ease-in-out\
          \ 1s infinite'\n    : 'none'\n]]]\n"
      icon:
      - opacity: 0.7
      - color: '[[[ return variables.color ]]]'
      - filter: drop-shadow( 0 0 2px rgba(0, 0, 0, .7))
      state:
      - font-size: 1.5em
      - font-weight: bold
      - text-shadow: 0 0 6px black
      - overflow: visible
title: BNet
views:
- badges: []
  cards:
  - cards:
    - color_type: label-card
      entity: light.all_lights
      name: Lights
      size: 30px
      type: custom:button-card
    - cards:
      - color_type: card
        entity: light.bedroom
        hold_action:
          action: more-info
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      - color_type: card
        double_tap_action:
          action:
          - data:
              brightness_pct: 50
              entity_id: light.lounge
            service: light.toggle
        entity: light.lounge
        hold_action:
          action: more-info
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      - color_type: card
        entity: light.office
        hold_action:
          action: more-info
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      type: horizontal-stack
    type: vertical-stack
  - columns: 3
    entities:
    - entity: light.bedroom
      name: Bedroom Light
      tap_action:
        action: toggle
    - entity: media_player.bedroom_ps4
    title: Bedroom
    type: glance
  - columns: 3
    entities:
    - entity: light.lounge
      name: Lounge Light
      tap_action:
        action: toggle
    - entity: switch.wol_spare
      icon: mdi:desktop-classic
      name: temp PC
      tap_action:
        action: toggle
    - entity: switch.wol_shif
      icon: mdi:desktop-classic
      name: Shif (NUC)
      tap_action:
        action: toggle
    - entity: media_player.lounge_ps4
    - entity: media_player.str_dn1080_9ba8db_2
      name: Lounge Amp
    - entity: switch.subwoofer
    - entity: switch.wol_lounge
      icon: mdi:desktop-classic
      name: Lounge PC
      tap_action:
        action: toggle
    title: Living Room
    type: glance
  - columns: 3
    entities:
    - entity: light.office
      name: Office Light
      tap_action:
        action: toggle
    - entity: switch.wol_workstation
      icon: mdi:desktop-classic
      name: Gaming Rig
      tap_action:
        action: toggle
    - entity: sensor.brother_mfc_9340cdw
    title: Office
    type: glance
  - entities:
    - entity: switch.pi_hole
    - entity: sensor.mikrotik_router_kib_s_received
      name: WAN (RX)
    - entity: sensor.mikrotik_router_kib_s_sent
      name: WAN (TX)
    title: Server Rack
    type: glance
  - entity: weather.home
    type: weather-forecast
  - cards:
    - entity: sensor.exchange_rate_1_btc
      type: entity
    - entity: input_number.btc_amount
      type: entity
    - entity: sensor.my_btc_value
      icon: mdi:dollar
      name: My BTC
      type: entity
      unit: NZD
    type: vertical-stack
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - entities:
    - entity: sensor.anniversary_swmbo
      name: Our Anniversary
    - entity: sensor.birthday_me
      name: My Birthday
    - entity: sensor.birthday_swmbo
      name: Her Birthday
    header:
      hold_action:
        action: none
      image: https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png
      tap_action:
        action: none
      type: picture
    show_header_toggle: false
    type: entities
  icon: mdi:calendar
  path: events
  title: Events
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
- badges: []
  cards:
  - dark_mode: false
    entities:
    - entity: device_tracker.g8142
    - entity: zone.work
    - entity: zone.home
    type: map
  - card:
      show_header_toggle: false
      title: Who's Home?
      type: entities
    filter:
      exclude:
      - state: not_home
      include:
      - entity_id: person.*
    show_empty: false
    sort: none
    type: custom:auto-entities
    unique: false
  - columns: 1
    entities:
    - entity: sensor.g8142_geocoded_location
    show_icon: true
    show_state: true
    title: Phone Location
    type: glance
  icon: mdi:crosshairs-gps
  path: location
  title: Location
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
- badges:
  - entity: sensor.mikrotik_router_kib_s_received
  - entity: sensor.mikrotik_router_kib_s_sent
  - entity: sensor.pi_hole_dns_queries_today
  - entity: sensor.pi_hole_ads_blocked_today
  cards:
  - cards:
    - cards:
      - entity: sensor.mikrotik_router_kib_s_sent
        max: 40000
        min: 0
        name: WAN TX
        severity:
          green: 0
          red: 35000
          yellow: 25000
        type: gauge
      - entity: sensor.mikrotik_router_kib_s_received
        max: 40000
        min: 0
        name: WAN RX
        severity:
          green: 0
          red: 35000
          yellow: 25000
        type: gauge
      type: horizontal-stack
    - card:
        show_header_toggle: false
        type: entities
      filter:
        include:
        - entity_id: sensor.mikrotik_router_*
      show_empty: true
      sort:
        ignore_case: true
        method: name
      type: custom:auto-entities
      unique: false
    title: Routerboard Stats
    type: vertical-stack
  - cards:
    - entity: sensor.pi_hole_ads_percentage_blocked_today
      max: 100
      min: 0
      name: Blocked Ad Percentage
      severity:
        green: 0
        red: 50
        yellow: 25
      theme: default
      type: gauge
    - card:
        show_header_toggle: false
        type: entities
      filter:
        include:
        - entity_id: sensor.pi*
      show_empty: true
      sort:
        ignore_case: true
        method: name
      type: custom:auto-entities
      unique: false
    title: Pi-Hole
    type: vertical-stack
  - cards:
    - entity: sensor.unifi_clients
      max: 50
      min: 0
      name: Devices
      severity:
        green: 10
        red: 25
        yellow: 15
      theme: default
      type: gauge
      unit: ' '
    - entities:
      - entity: sensor.unifi_clients
        icon: mdi:wifi
        name: ' '
        secondary_info: 'Berserkir-Net : [[ if(sensor.unifi_clients.attributes.Berserkir-Net
          == undefined, "0", sensor.unifi_clients.attributes.Berserkir-Net) ]] <br>GuestNet
          : [[ if(sensor.unifi_clients.attributes.GuestNet == undefined, "0", sensor.unifi_clients.attributes.GuestNet)
          ]]'
        type: custom:secondaryinfo-entity-row
      type: entities
    - entities:
      - entity: sensor.state_loungeap
      - entity: sensor.state_officeap
        icon: mdi:access-point-network
      - entity: sensor.state_outdoorap
        icon: mdi:access-point-network
      show_header_toggle: false
      type: entities
    title: UniFi Access Point Status
    type: vertical-stack
  icon: mdi:network
  path: network
  title: Network
- badges:
  - entity: switch.wol_lounge
  - entity: switch.wol_shif
  - entity: switch.wol_workstation
  cards:
  - cards:
    - cards:
      - color_type: card
        entity: switch.wol_lounge
        name: Lounge HTPC
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      - color_type: card
        entity: switch.wol_shif
        name: Lounge NUC
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      type: horizontal-stack
    - cards:
      - color_type: card
        entity: switch.wol_workstation
        name: Workstation
        size: 30px
        tap_action:
          action: toggle
        type: custom:button-card
      type: horizontal-stack
    type: vertical-stack
  icon: mdi:dip-switch
  panel: false
  path: wakeonlan
  title: WakeOnLan
- badges: []
  cards:
  - card:
      show_header_toggle: false
      title: OWM
      type: entities
    filter:
      include:
      - entity_id: sensor.openweathermap*
    sort: name
    type: custom:auto-entities
    unique: false
  - entities:
    - entity: sensor.new_zealand_coronavirus_confirmed
      name: Confirmed
    - entity: sensor.new_zealand_coronavirus_current
      name: Current
    - entity: sensor.new_zealand_coronavirus_deaths
      name: Deaths
    - entity: sensor.new_zealand_coronavirus_recovered
      name: Recovered
    title: COVID-19
    type: glance
  - entity: weather.home
    type: weather-forecast
  icon: mdi:weather-partly-cloudy
  path: weather
  title: Weather
- badges:
  - entity: sensor.plex_berserkirnet
    name: Plex Streams
  - entity: sensor.plextotalbandwidthrounded
    name: Plex Bandwidth
  - entity: sensor.nzbget_speed
  - entity: sensor.ombi_pending_requests
    name: Pending Requests
  cards:
  - card:
      show_header_toggle: false
      title: Plex Media
      type: entities
    filter:
      include:
      - entity_id: sensor.berserkirnet_library*
    sort: name
    type: custom:auto-entities
    unique: false
  - cards:
    - entities:
      - entity: sensor.sonarr_shows
      - entity: sensor.sonarr_upcoming
      show_header_toggle: false
      title: Sonarr
      type: entities
    - entities:
      - entity: sensor.radarr_movies
      - entity: sensor.radarr_upcoming
      show_header_toggle: false
      title: Radarr
      type: entities
    - entities:
      - entity: switch.nzbget_download
      - entity: sensor.nzbget_queue_size
      - entity: sensor.nzbget_speed
      title: NZBGet
      type: entities
    type: vertical-stack
  - card:
      show_header_toggle: false
      title: Now Streaming
      type: entities
    filter:
      exclude:
      - state: unavailable
      - state: idle
      include:
      - entity_id: media_player.plex_*
    show_empty: true
    sort: none
    type: custom:auto-entities
    unique: false
  - entity: media_player.spotify_sky_girl14
    type: media-control
  - cards:
    - entity: sensor.plex_berserkirnet
      name: Current Plex Streams
      type: sensor
    - entity: sensor.plexwanbandwidthrounded
      name: Plex WAN Bandwith
      type: sensor
    - entity: sensor.plexlanbandwidthrounded
      name: Plex LAN Bandwith
      type: sensor
    - entity: sensor.plextotalbandwidthrounded
      name: Plex Total Bandwidth
      type: sensor
    type: vertical-stack
  - entity: media_player.str_dn1080_9ba8db_2
    type: media-control
  icon: mdi:film
  panel: false
  path: media
  theme: Backend-selected
  title: Media
- badges: []
  cards:
  - aspect_ratio: 100%
    type: iframe
    url: https://media.berserkir.net/recentlyadded/
  icon: mdi:filmstrip
  panel: true
  path: recently-added
  title: Recently Added
- badges: []
  cards:
  - card:
      secondary_info: game
      show_header_toggle: false
      title: Steam Friends
      type: entities
    filter:
      include:
      - entity_id: sensor.steam*
    show_empty: true
    sort:
      ignore_case: true
      method: name
    type: custom:auto-entities
    unique: false
  - cards:
    - entity: media_player.bedroom_ps4
      type: media-control
    - entity: media_player.lounge_ps4
      type: media-control
    type: vertical-stack
  - entities:
    - entity: sensor.steam_76561198056470571
      secondary_info:
        '[object Object]': null
    - entity: sensor.steam_76561198151879355
    - entity: sensor.steam_76561198120534583
    - entity: sensor.steam_76561197992785642
    show_header_toggle: false
    title: Steamers
    type: entities
  icon: mdi:gamepad-variant
  path: gaming
  title: Gaming
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
- badges: []
  cards:
  - cards:
    - dark_mode: false
      entities:
      - entity: device_tracker.g8142
      hours_to_show: 0
      title: Phone Location
      type: map
    - entities:
      - entity: sensor.battery_level
        name: Battery
      - entity: binary_sensor.g8142_is_charging
        name: Charging?
      - entity: binary_sensor.g8142_music_active
        name: Media?
      - entity: binary_sensor.g8142_interactive
        name: In Use?
      title: Phone State
      type: glance
    - card:
        show_header_toggle: false
        title: Phone Sensors
        type: entities
      filter:
        exclude:
        - entity_id: sensor.g8142_geo*
        include:
        - entity_id: sensor.g8142*
      show_empty: false
      type: custom:auto-entities
      unique: false
    type: vertical-stack
  icon: mdi:phone
  panel: false
  path: phones
  title: Phones
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
- badges: []
  cards:
  - color: darkgray
    custom_fields:
      c:
        card:
          entity: sensor.brother_mfc_9340cdw_cyan_toner_cartridge
          template: inkwell
          type: custom:button-card
          variables:
            color: cyan
      k:
        card:
          entity: sensor.brother_mfc_9340cdw_black_toner_cartridge
          template: inkwell
          type: custom:button-card
          variables:
            color: black
      m:
        card:
          entity: sensor.brother_mfc_9340cdw_magenta_toner_cartridge
          template: inkwell
          type: custom:button-card
          variables:
            color: magenta
      y:
        card:
          entity: sensor.brother_mfc_9340cdw_yellow_toner_cartridge
          template: inkwell
          type: custom:button-card
          variables:
            color: yellow
    entity: sensor.brother_mfc_9340cdw
    name: MFC-9340
    show_state: true
    styles:
      card:
      - padding: 0 0 5px 0
      custom_fields:
        c:
        - width: 80%
        - margin: auto
        k:
        - width: 80%
        - margin: auto
        m:
        - width: 80%
        - margin: auto
        y:
        - width: 80%
        - margin: auto
      grid:
      - grid-template-areas: '"i c m y k" "n s s s s"'
      - grid-template-columns: 1fr 1fr 1fr 1fr 1fr
      - grid-template-rows: auto 1em
      icon:
      - width: 100%
      state:
      - text-align: center
      - width: 100%
    type: custom:button-card
  - entities:
    - entity: sensor.mfc_9340cdw_status
    - entity: sensor.mfc_9340cdw_page_counter
    - entity: sensor.mfc_9340cdw_b_w_counter
    - entity: sensor.mfc_9340cdw_color_counter
    - entity: sensor.mfc_9340cdw_belt_unit_remaining_life
    - entity: sensor.mfc_9340cdw_fuser_remaining_life
    - entity: sensor.mfc_9340cdw_pf_kit_1_remaining_life
    - entity: sensor.mfc_9340cdw_cyan_drum_remaining_life
    - entity: sensor.mfc_9340cdw_magenta_drum_remaining_life
    - entity: sensor.mfc_9340cdw_black_drum_remaining_life
    - entity: sensor.mfc_9340cdw_yellow_drum_remaining_life
    state_color: false
    type: entities
  icon: mdi:printer
  path: ''
  title: Printers
- badges: []
  cards:
  - card:
      show_header_toggle: false
      title: Repea
      type: entities
    filter:
      include:
      - entity_id: sensor.repea*
    sort: name
    type: custom:auto-entities
    unique: false
  icon: mdi:nas
  path: nas
  title: NAS
- badges: []
  cards:
  - alias:
      ko: No update for the moment...
      ok: Update available !
    color:
      icon: grey
    entity: binary_sensor.updater
    hours_to_show: 168
    icon: mdi:raspberry-pi
    name: HA update
    show:
      footer: false
    status_adaptive_color: true
    type: custom:uptime-card
  - cards:
    - entities:
      - entity: input_text.git_message
        name: Message
      type: entities
    - card:
        entity: input_boolean.git_commit
        hold_action:
          action: none
        icon: mdi:github
        icon_height: 45px
        show_state: false
        tap_action:
          action: call-service
          service: automation.trigger
          service_data:
            entity_id: automation.commit_message
        type: button
      conditions:
      - entity: input_text.git_message
        state_not: Committed from UI without a message
      type: conditional
    title: Git Commands
    type: vertical-stack
  - entities:
    - sensor.hass_repo
    - sensor.ombi_docs
    show_extended: true
    show_github_icon: true
    title: Git Repo
    type: custom:github-card
  - cards:
    - hold_action:
        action: none
      icon: mdi:monitor-screenshot
      icon_height: 45px
      name: Convert Lovelace to Yaml
      tap_action:
        action: call-service
        service: shell_command.convert_lovelace
      type: button
    - hold_action:
        action: none
      icon: mdi:github
      name: Commit Update
      tap_action:
        action: call-service
        service: shell_command.commit_new_version
      type: button
    type: grid
  icon: mdi:git
  path: git
  title: Git
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
- badges: []
  cards:
  - entities:
    - switch.subwoofer
    - sensor.subwoofer_amps
    - sensor.subwoofer_watts
    - sensor.subwoofer_today_kwh
    - sensor.subwoofer_total_kwh
    - sensor.subwoofer_volts
    type: entities
  icon: mdi:dev-to
  panel: false
  path: testing
  title: Testing
  visible:
  - user: 08d29e434e9a4bed98b3a62218eac7a7
  - user: b6db76d5cfd24c73b9acc55e08c0ebd5
