###########################################
# Bitcoin
###########################################
- platform: bitcoin
  currency: NZD
  display_options:
    - exchangerate
    - difficulty
###########################################
# Ethereum
###########################################
