###########################################
# Bitcoin
###########################################
- platform: bitcoin
  currency: NZD
  display_options:
    - exchangerate
    - difficulty

###########################################
# Cryptonator
###########################################
- platform: cryptostate
  resources:
    #Example of the first formula
    - compare: btc-nzd
      name: Bitcoin
    - compare: eth-nzd
      name: Ethereum
    - compare: zec-nzd
      name: ZCash
