###########################################
# Movie Sensors
###########################################
- platform: radarr
  api_key: !secret radarr_api
  host: !secret media_server_url
  urlbase: !secret radarr_baseurl
  ssl: true
  port: 443
  days: 1
  monitored_conditions:
    - upcoming
    - movies
