# This file generates the extra sensors for tautulli - they're just attributes, but splitting out via template.
- platform: template
  sensors:
    total_bandwidth_mbps:
      value_template: "{{ (int(states('sensor.total_bandwidth')) / 1024) }}"
      unit_of_measurement: "Mbps"
    total_bandwidth_mbps_rounded:
      value_template: "{{ (int(states('sensor.total_bandwidth')) / 1024) | round(2) }}"
      unit_of_measurement: "Mbps"
