# This is the template that works out the value of the wallet amount based on the input amount.
- platform: template
  sensors:
    kettle_temperature:
      friendly_name: Kettle Temperature
      value_template: "{{ (state_attr('climate.kettle', 'current_temperature')) }}"
      unit_of_measurement: "°C"
