# This template will give me a 'printer status' sensor.
- platform: template
  sensors:
    printer_state_reason:
      friendly_name: Printer State Reason
      value_template: "{{ (state_attr('sensor.brother_mfc_9340cdw', 'state_reason')) }}"
    printer_state_message:
      friendly_name: Printer State Message
      value_template: "{{ (state_attr('sensor.brother_mfc_9340cdw', 'state_message')) }}"
