# This is the template that works out the value of the wallet amount based on the input amount.
- platform: template
  sensors:
    my_btc_value:
      value_template: "{{ (states('sensor.exchange_rate_1_btc') | float * states('input_number.btc_amount') | float) | round(2) }}"
