- platform: template
  sensors:
    hour_of_power:
      friendly_name: "Hour of Power"
      value_template: >
        {{ states('sensor.hour_of_free_power_start') < utcnow().strftime('%Y-%m-%dT%H:%M') < states('sensor.hour_of_free_power_end') }}
