- platform: template
  sensors:
    # Access Points
    state_loungeswitch:
      friendly_name: "Lounge Switch"
      value_template: '{% if is_state("device_tracker.loungeswitch", "home") %}Online{% else %}Offline{% endif %}'
      icon_template: >-
        '{% if is_state("device_tracker.loungeswitch", "home") %}
           mdi:lan-connect
         {% else %}
           mdi:lan-disconnect
         {% endif %}'
    state_loungeap:
      friendly_name: "Lounge AP"
      value_template: '{% if is_state("device_tracker.loungeap", "home") %}Online{% else %}Offline{% endif %}'
      icon_template: >-
        '{% if is_state("device_tracker.loungeap", "home") %}
           mdi:access-point-network
         {% else %}
           mdi:access-point-network-off
         {% endif %}'
    state_officeap:
      friendly_name: "Office AP"
      value_template: '{% if is_state("device_tracker.officeap", "home") %}Online{% else %}Offline{% endif %}'
      icon_template: >-
        '{% if is_state("device_tracker.officeap", "home") %}
           mdi:access-point-network
         {% else %}
           mdi:access-point-network-off
         {% endif %}'
    state_garageap:
      friendly_name: "Garage AP"
      value_template: '{% if is_state("device_tracker.garageap", "home") %}Online{% else %}Offline{% endif %}'
      icon_template: >-
        '{% if is_state("device_tracker.garageap", "home") %}
           mdi:access-point-network
         {% else %}
           mdi:access-point-network-off
         {% endif %}'
