# This is a template that gives me a dedicated sensor for kettle temperature, rather than just an attribute.
- platform: template
  sensors:
    bedroom_temperature:
      unique_id: bedroom_temperature
      friendly_name: Bedroom Temperature
      value_template: "{{ (state_attr('climate.bedroom_heater', 'current_temperature')) }}"
      unit_of_measurement: "°C"
    bedroom_humidity:
      unique_id: bedroom_humidity
      friendly_name: Bedroom Humidity
      value_template: "{{ (state_attr('climate.bedroom_heater', 'current_humidity')) }}"
      unit_of_measurement: "%"
    server_rack_temperature:
      unique_id: server_rack_temperature
      friendly_name: Server Rack Temperature
      value_template: "{{ (state_attr('climate.server_rack_fans', 'current_temperature')) }}"
      unit_of_measurement: "°C"
    server_rack_humidity:
      unique_id: server_rack_humidity
      friendly_name: Server Rack Humidity
      value_template: "{{ (state_attr('climate.server_rack_fans', 'current_humidity')) }}"
      unit_of_measurement: "%"
