- alias: "Lovelace: convert lovelace.json to lovelace-ui.yaml"
  initial_state: "on"
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  action:
    service: shell_command.convert_lovelace
