- platform: template
  sensors:
    subwoofer_switch_amps:
      friendly_name_template: "{{ state_attr('switch.subwoofer_switch','friendly_name') }} Current"
      value_template: "{{ state_attr('switch.subwoofer_switch','current_a') }}"
      unit_of_measurement: "A"
    subwoofer_switch_watts:
      friendly_name_template: "{{ state_attr('switch.subwoofer_switch','friendly_name') }} Current Consumption"
      value_template: "{{ state_attr('switch.subwoofer_switch','current_power_w') }}"
      unit_of_measurement: "W"
    subwoofer_switch_total_kwh:
      friendly_name_template: "{{ state_attr('switch.subwoofer_switch','friendly_name') }} Total Consumption"
      value_template: "{{ state_attr('switch.subwoofer_switch','total_energy_kwh') }}"
      unit_of_measurement: "kWh"
    subwoofer_switch_volts:
      friendly_name_template: "{{ state_attr('switch.subwoofer_switch','friendly_name') }} Voltage"
      value_template: "{{ state_attr('switch.subwoofer_switch','voltage') }}"
      unit_of_measurement: "V"
    subwoofer_switch_today_kwh:
      friendly_name_template: "{{ state_attr('switch.subwoofer_switch','friendly_name') }} Today's Consumption"
      value_template: "{{ state_attr('switch.subwoofer_switch','today_energy_kwh') }}"
      unit_of_measurement: "kWh"
