# All Lights
- platform: group
  name: Every Light
  entities:
    - light.bedroom_lamp
    - light.lounge_lamp
    - light.office_lamp
    - light.bedroom_light
    - light.lounge_light
    - light.office_light
    - light.hall_light_strip
    - light.kitchen_switch_kitchen_light
    - light.kitchen_switch_dining_light
    - light.kitchen_switch_pantry_light
    - light.garage_switch_bench
    - light.garage_switch_overhead
    - light.garage_switch_driveway
# All Roof Lights
- platform: group
  name: All Lights
  entities:
    - light.bedroom_light
    - light.lounge_light
    - light.office_light
    - light.hall_light_strip
# All Lamps
- platform: group
  name: All Lamps
  entities:
    - light.bedroom_lamp
    - light.lounge_lamp
    - light.office_lamp
# Lounge Lights
- platform: group
  name: Lounge Lights
  entities:
    - light.lounge
    - light.lounge_lamp
# Hall Lights
- platform: group
  name: Hall Lights
  entities:
    - light.smart_rgb_light_strip
# Bedroom Lights
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom
    - light.bedroom_lamp
# Office Lights
- platform: group
  name: Office Lights
  entities:
    - light.office_light
    - light.office_lamp
# Kitchen Lights
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_switch_kitchen_light
    - light.kitchen_switch_dining_light
    - light.kitchen_switch_pantry_light
# Garage Lights
- platform: group
  name: Garage Lights
  entities:
    - light.garage_switch_bench
    - light.garage_switch_overhead
    - light.garage_switch_driveway
